swagger: "2.0"
info:
  title: Ping API
  description: Parameterized endpoint(s) to receive pong JSON response
  version: 1.0.0
host: api.example.com
basePath: /
schemes:
  - http
paths:
  /:
    get:
      summary: Homepage
      operationId: getHome
      responses:
        '200':
          description: Successful operation
          content:
            string 

  /test/{key}:
    get:
      summary: Returns a pong JSON response if the key is ping
      operationId: getPing 
      parameters:
        - key: key
	in: path
	description: Example
	required: true
        schema:
	  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json
